### ISSUE TITLE
composer require incorrect

### ISSUE THREAD

**Issue by seedgabo** [Krato/Laravel-5-Config-Manager#1]
it's seems the composer require is incorrect

**Comment by Krato** [comment]
@seedgabo Which is the error?

**Comment by HDVinnie** [comment]
[InvalidArgumentException]                                                   
  Could not find package infinety-es/configmanager at any version for your mi  
  nimum-stability (RC). Check the package spelling or your minimum-stability

**Comment by Krato** [comment]
Fixed!
