### ISSUE TITLE
Error Service Provider

### ISSUE THREAD

**Issue by HDVinnie** [Krato/Laravel-5-Config-Manager#3]
Installed via composer and now works thanks for fix....

added Infinety\Config\ConfigManagerServiceProvider::class, to config/app.php

php artisan vendor:publish --provider="Infinety\ConfigManager\ConfigManagerServiceProvider"

RESULTS IN:
                                                                 
  [Symfony\Component\Debug\Exception\FatalThrowableError]         
  Class 'Infinety\Config\ConfigManagerServiceProvider' not found  

Is there supposed to be a Class Aliases added as well to the config/app.php?

**Comment by Krato** [comment]
And what is the result if you call `php artisan vendor:publish`?

**Comment by HDVinnie** [comment]
[Symfony\Component\Debug\Exception\FatalThrowableError]         
  Class 'Infinety\Config\ConfigManagerServiceProvider' not found

Same being seen on my apps webpages via debug view

**Comment by Krato** [comment]
Sure please. Change it to:
```
Infinety\ConfigManager\ConfigManagerServiceProvider::class,
```

Readme updated.
