### ISSUE TITLE
updating the display after saving doesnt work for nested keys

### ISSUE THREAD

**Issue by DoDSoftware** [Krato/Laravel-5-Config-Manager#5]
Given this config:

```
<?php

return [
    'it' => [
        'url'      => 'https://site.com',
        'username' => 'username',
        'password' => 'password',
    ],
];

```

After saving  a new value for  it.url, the display does not update. That is to say, the `td` is not updated with the new value on the page. 

This is because the resulting html for that row is:

```
<tr id="key_it.url">
  <td class="key">it.url</td>
  <td class="value">https://site.com</td>
  <td>
    <button class="btn btn-sm btn-default edit" data-placement="top" data-key="it.url" data-loading-text="Saving new key..." data-original-title="" title=""><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button>
  </td>
</tr>

```
And jQuery call is looking for:

`$row = $("#key_"+key);  // key = it.url`

Which evaluates to `$row = $("#key_it.url");` which looks for an element with an id of `key_it` and a class of `url` which of course doesn't exist.

For this reason, literal periods in selectors must be escaped.

Updating the code to call `var $row = $("#key_"+key.replace('.', '\\.'));` fixes this problem by properly escaping any periods in the id selector

See [How to select html nodes by ID with jquery when the id contains a dot?](http://stackoverflow.com/questions/605630/how-to-select-html-nodes-by-id-with-jquery-when-the-id-contains-a-dot)

**Comment by DoDSoftware** [comment]
I added a pull request with the fix. Nice start on this project. If I have time, I may work on adding functionality to add new keys and create new files.

**Comment by Krato** [comment]
Thanks for your pull. Is now merged 😀
