### ISSUE TITLE
Difference to https://github.com/Brotzka/laravel-dotenv-editor

### ISSUE THREAD

**Issue by wowcut** [Krato/Laravel-5-Config-Manager#7]
Hi, nice project - it would be very interesting to read about the main differences between this project and https://github.com/Brotzka/laravel-dotenv-editor - what features does this project provide that does not come with the one mentioned? Thanks!

**Comment by Krato** [comment]
Hi @wowcut!

Both packages are similar, a graphical way to edit files.

The difference is that my package is able to edit config files inside `config`folder, and https://github.com/Brotzka/laravel-dotenv-editor is to edit .env project file.

Regards!

**Comment by wowcut** [comment]
Thanks for the info!
