### ISSUE TITLE
Update Fails

### ISSUE THREAD

**Issue by HDVinnie** [Krato/Laravel-5-Config-Manager#9]
Hello,

When I try to update a config in the manager it fails.

Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500)  https://mydomain.com/staff_dashboard/config_settings/update

Any idea why?

**Comment by Krato** [comment]
Can you give me more info?

Error log for example.

Thanks

**Comment by HDVinnie** [comment]
ErrorException: file_put_contents(/var/www/html/config/other.php): failed to open stream: Permission denied in /var/www/html/vendor/infinety-es/config/src/Rewrite.php:29
